// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from geeklink.djinni

#import <Foundation/Foundation.h>

/**常用动作类型 */
typedef NS_ENUM(NSInteger, GLActionFullType)
{
    GLActionFullTypeInsert,
    GLActionFullTypeDelete,
    GLActionFullTypeUpdate,
    GLActionFullTypeTest,
};
