// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from define_key_type.djinni

#import <Foundation/Foundation.h>

/**载波类型 */
typedef NS_ENUM(NSInteger, GLCarrierType)
{
    GLCarrierTypeCARRIERRESERVE,
    GLCarrierTypeCARRIER20,
    GLCarrierTypeCARRIER26,
    GLCarrierTypeCARRIER28,
    GLCarrierTypeCARRIER31,
    GLCarrierTypeCARRIER33,
    GLCarrierTypeCARRIER36,
    GLCarrierTypeCARRIER38,
    GLCarrierTypeCARRIER40,
    GLCarrierTypeCARRIER42,
    GLCarrierTypeCARRIER54,
    GLCarrierTypeCARRIER56,
    GLCarrierTypeCARRIER64,
};
