// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from device_handle.djinni

#import <Foundation/Foundation.h>

/**
 *设备连接状态描述
 *offline; 连接断开
 *local;   本地连接
 *remote;  远程连接
 *need_bind_again;  需要重新绑定添加
 */
typedef NS_ENUM(NSInteger, GLDevConnectState)
{
    GLDevConnectStateOffline,
    GLDevConnectStateLocal,
    GLDevConnectStateRemote,
    GLDevConnectStateNeedBindAgain,
};
