// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from device_handle.djinni

#import <Foundation/Foundation.h>

/**
 *key_study_ir;学习红外
 *key_study_315M;学习315M
 *key_study_433M;学习433M
 *key_study_com;组合学习
 */
typedef NS_ENUM(NSInteger, GLKeyStudyType)
{
    GLKeyStudyTypeKeyStudyIr,
    GLKeyStudyTypeKeyStudy315M,
    GLKeyStudyTypeKeyStudy433M,
    GLKeyStudyTypeKeyStudyCom,
    GLKeyStudyTypeKeyStudyMatch,
    GLKeyStudyTypeKeyStudyCancel,
};
