// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from device_smart_pi.djinni

#import <Foundation/Foundation.h>

/**
 *单品智能定时动作
 *insert 增
 *delete 删
 *update 改
 *set_on_off 只设置开关
 */
typedef NS_ENUM(NSInteger, GLSingleTimerActionType)
{
    GLSingleTimerActionTypeInsert,
    GLSingleTimerActionTypeDelete,
    GLSingleTimerActionTypeUpdate,
    GLSingleTimerActionTypeSetOnOff,
};
