// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from device_handle.djinni

#import <Foundation/Foundation.h>

/**
 *timezone_get;获取设备的时区
 *timezone_set;设置设备的时区
 *timezone_lang_set;设置设备的推送语言
 */
typedef NS_ENUM(NSInteger, GLTimezoneAction)
{
    GLTimezoneActionTimezoneActionGet,
    GLTimezoneActionTimezoneActionSet,
};
